# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 877d8f7c42e3ae4fc6e115ec0c8048ff841efd66d09fd895b55612890607a3b7591dd31b386b93a75444c85e543838d13a63f1d4cbc95e562beadfa5168cf6be

test:
  secret_key_base: 55397c698bd481bf2a72af875f4b7f86f65e3c48c75f7ae61e0e46155225ab665bbf03833b66b3078118a2787d908c463901a9840a27f3eda8496bed92d6eae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
